config/routes.rb
Rails.application.routes.draw do
  resources :app_users
  resources :emergencies
  resources :especialidades
  root 'welcome#index'

  devise_for :users
  resources :points
  get '/calculate/' => 'route#calculate'
  get '/usuarios' => 'usuarios#index'
  get '/usuarios/new' => 'usuarios#new'
  post '/usuarios' => 'usuarios#create'
  get '/user/:id/edit_user' => 'usuarios#edit'
  post '/user/:id/update_user' => 'usuarios#update_user'
  get '/enlazar/:id' => 'points#enlazar'
  get '/enlazarEmergencias/:id' => 'points#enlazarEmergencias'
  post 'create/enlazar/:id' => 'points#cenlazar'
  post 'create/enlazarEmergencias/:id' => 'points#cenlazarEmergencias'
  get '/list/points' => 'points#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace 'api' do
    namespace 'v1' do
       resources :points
       get '/points/get/:id' => 'points#especialidades'
       get '/especialidades' => 'points#getAllespecialidades'
       get '/especialidades/:id' => 'points#getAllCentrosofEspecialidad'
       get '/emergencias' => 'points#getAllemergencias'
       get '/emergencias/:id' => 'points#getAllCentrosofEmergencia'
       get '/user' => 'points#getUser'

    end
  end
end

app/models/especialidade.rb
class Especialidade < ApplicationRecord
  has_many :has_especialidades
  has_many :points, through: :has_especialidades
end

app/controllers/especialidades_controller.rb
class EspecialidadesController < ApplicationController
  before_action :set_especialidade, only: [:show, :edit, :update, :destroy]

  # GET /especialidades
  # GET /especialidades.json
  def index
    @nombre = params[:nombre]
    if @nombre
      @specialidades = Especialidade.where("name like ?", "%#{@nombre}%")
      @especialidades = @specialidades.order('name ASC')
    else
      @especialidades = Especialidade.order('name ASC')
    end
  end

  # GET /especialidades/1
  # GET /especialidades/1.json
  def show
  end

  # GET /especialidades/new
  def new
    @especialidade = Especialidade.new
  end

  # GET /especialidades/1/edit
  def edit
  end

  # POST /especialidades
  # POST /especialidades.json
  def create
    @especialidade = Especialidade.new(especialidade_params)

    respond_to do |format|
      if @especialidade.save
        format.html { redirect_to especialidades_url, notice: '' }
        format.json { render :show, status: :created, location: @especialidade }
      else
        format.html { render :new }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especialidades/1
  # PATCH/PUT /especialidades/1.json
  def update
    respond_to do |format|
      if @especialidade.update(especialidade_params)
        format.html { redirect_to especialidades_url, notice: '' }
        format.json { render :show, status: :ok, location: @especialidade }
      else
        format.html { render :edit }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especialidades/1
  # DELETE /especialidades/1.json
  def destroy
    HasEspecialidade.where(:especialidade_id => @especialidade.id).destroy_all
    @especialidade.destroy
    respond_to do |format|
      format.html { redirect_to especialidades_url, notice: 'Especialidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especialidade
      @especialidade = Especialidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especialidade_params
      params.require(:especialidade).permit(:name)
    end
end

app/helpers/especialidades_helper.rb
module EspecialidadesHelper
end

app/views/especialidades/_form.html.erb
<% if user_signed_in?  && current_user.role == "Administrador" %>
<%= form_with(model: especialidade, local: true) do |form| %>
  <% if especialidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(especialidade.errors.count, "error") %> prohibited this especialidade from being saved:</h2>

      <ul>
      <% especialidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :especialidade_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%else%>
<script type="text/javascript">
   window.location.href="/users/sign_in"  // put your correct path in a string here
</script>
<% end %>

app/views/especialidades/edit.html.erb
<h1>Editing Especialidade</h1>

<%= render 'form', especialidade: @especialidade %>

<%= link_to 'Show', @especialidade %> |
<%= link_to 'Back', especialidades_path %>

app/views/especialidades/index.html.erb
<div class="jumbotron container">
  <div class="text-center">
  <h3>Lista de Especialidades</h3>
  <hr>
  <div class="container">
    <form action="/especialidades" method="get">
      <input class="form-control form-group" placeholder="Ingrese el nombre de la especialidad" value="<%= @nombre %>" name=nombre type="text">
      <button class="btn btn-warning btn-block form-group" type=”submit”>Buscar</button>
    </form>
  </div>
</div>
  <br>

  <div class="container">
    <table class="table">
          <thead class="table-light">
            <tr>
              <th>#</th>
              <th>Nombre</th>
              <th>Opciones</th>
            </tr>
          </thead>
          <tbody>
            <% @count=0 %>
            <% @especialidades.each do |especialidade| %>
              <tr class="table-light">
                <td><%= @count=@count+1%></td>
                <td><%= especialidade.name %></td>
                <td><%= link_to link_to ('<i class="fa fa-eye" aria-hidden="true"></i>').html_safe, especialidade , :class => 'btn btn-primary  btn-sm' %>
                <%if current_user.role == "Administrador"%>
                <a class="btn btn-warning btn-sm" href="#myModal<%=especialidade.id%>" data-toggle="modal" data-target="#myModal<%=especialidade.id%>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                <%= link_to ('<i class="fa fa-trash-o" aria-hidden="true"></i>').html_safe , especialidade, :class => 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
               </td>
              </tr>
              <div class="modal fade" id="myModal<%=especialidade.id%>">
                <div class="modal-dialog">
                    <div class="modal-content">
                      <form action="/especialidades/<%=especialidade.id%>" method="post">
                      <input type="hidden" name="_method" value="patch">
                       <div class="modal-header">
                        <h4 class="modal-title">Editando emergencia</h4>
                       </div>
                      <div class="modal-body">
                         <div class="form-group">
                           <input  class="form-control" type="text" id="especialidade_name" name="especialidade[name]" value="<%= especialidade.name %>" placeholder="ingrese el nombre de la emergencia" required>
                         </div>
                      </div>
                      <div class="modal-footer">
                        <a href="#" data-dismiss="modal" class="btn btn-danger">Cancelar</a>
                        <input type="submit" class="btn btn-success" name="" value="Guardar">
                      </div>
                    </form>
                    </div>
                  </div>
              </div>
            <% end %>
          </tbody>
    </table>
  </div>
<br>
</div>

app/views/especialidades/new.html.erb
<h1>New Especialidade</h1>

<%= render 'form', especialidade: @especialidade %>

<%= link_to 'Back', especialidades_path %>

app/views/especialidades/show.html.erb
<% if user_signed_in?%>
<div class="jumbotron container">
  <div class="text-center">
    <h3><strong>  <%= @especialidade.name %></strong></h3>
  </div>
  <hr>
  <h5>Centros asociados a esta especialidad: </h5>
  <br>
  <% @especialidade.points.order('nombre ASC').each do |centro| %>
    <a href="/points/<%= centro.id %>" class="list-group-item list-group-item-action"><%=centro.nombre%></a>
  <% end %>
</div>
<%else%>
<script type="text/javascript">
   window.location.href="/users/sign_in"  // put your correct path in a string here
</script>
<% end %>