config/routes.rb
Rails.application.routes.draw do
  resources :app_users
  resources :emergencies
  resources :especialidades
  root 'welcome#index'

  devise_for :users
  resources :points
  get '/calculate/' => 'route#calculate'
  get '/usuarios' => 'usuarios#index'
  get '/usuarios/new' => 'usuarios#new'
  post '/usuarios' => 'usuarios#create'
  get '/user/:id/edit_user' => 'usuarios#edit'
  post '/user/:id/update_user' => 'usuarios#update_user'
  get '/enlazar/:id' => 'points#enlazar'
  get '/enlazarEmergencias/:id' => 'points#enlazarEmergencias'
  post 'create/enlazar/:id' => 'points#cenlazar'
  post 'create/enlazarEmergencias/:id' => 'points#cenlazarEmergencias'
  get '/list/points' => 'points#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace 'api' do
    namespace 'v1' do
       resources :points
       get '/points/get/:id' => 'points#especialidades'
       get '/especialidades' => 'points#getAllespecialidades'
       get '/especialidades/:id' => 'points#getAllCentrosofEspecialidad'
       get '/emergencias' => 'points#getAllemergencias'
       get '/emergencias/:id' => 'points#getAllCentrosofEmergencia'
       get '/user' => 'points#getUser'

    end
  end
end

app/controllers/route_controller.rb
class RouteController < ApplicationController

  class Ruta
    def initialize(id, lat, long, distance)
        @id = id
        @lat = lat
        @long = long
        @distance = distance
    end
  end

  def calculate
    @points = Point.all
    @dato = Ruta.new("","","","")
    @datos = []

  end
end

app/helpers/route_helper.rb
module RouteHelper
end

app/views/route/calculate.html.erb
<head>
 <style>
   /* Always set the map height explicitly to define the size of the div
    * element that contains the map. */
   #map {
     height: 100%;
   }
   /* Optional: Makes the sample page fill the window. */
   html, body {
     height: 100%;
     margin: 0;
     padding: 0;
   }
 </style>
</head>
<body>
  <p id="notice"><%= notice %></p>

  <h1>Points</h1>

  <table>
    <thead>
      <tr>
        <th>Latitude</th>
        <th>Longitude</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @points.each do |point| %>
        <tr>
          <td><%= point.latitude %></td>
          <td><%= point.longitude %></td>
          <td><%= link_to 'Show', point %></td>
          <td><%= link_to 'Edit', edit_point_path(point) %></td>
          <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
  </table>

  <br>

  <script>
    function initMap() {
      var myLatLng2 = {lat: -17.4073413, lng: -66.1551427};
      var posicioninicial = "-17.4073413,-66.1551427"

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 14,
        center: myLatLng2
      });

      var marker = new google.maps.Marker({
        position: myLatLng2,
        map: map,
        title: 'pocision inicial'
      });

       var objConfigDR = {
         map: map
       }

       <% @points.each do |point| %>
             var objConfigDS = {
               origin: posicioninicial, //latLong - String domicilio
               destination:"<%= point.latitude %>,<%= point.longitude %>",
               travelMode: google.maps.TravelMode.DRIVING
             }

             var ds = new google.maps.DirectionsService(); //cambia depende el servicio de transporte
             var dr = new google.maps.DirectionsRenderer(objConfigDR);

             ds.route(objConfigDS, fnRutear);

             function fnRutear( resultados, status){
               //muestra la linea entre A y B
               if (status == 'OK'){
                 document.getElementById('distance').innerHTML +=
                   resultados.routes[0].legs[0].distance.value + " meters";
                
                   <% @datos << @dato %>

                // Display the duration:
                document.getElementById('duration').innerHTML +=
                   resultados.routes[0].legs[0].duration.value + " seconds";
                 dr.setDirections(resultados);
               }else {
                 alert('Error'+ status);
               }
             };
       <% end %>

    }
  </script>

  <%= link_to 'New Point', new_point_path %>
  <div id="map"></div>
  <div id="duration">Duration: </div>
  <div id="distance">Distance: </div>
  <br><br>

</body>