config/routes.rb
Rails.application.routes.draw do
  resources :app_users
  resources :emergencies
  resources :especialidades
  root 'welcome#index'

  devise_for :users
  resources :points
  get '/calculate/' => 'route#calculate'
  get '/usuarios' => 'usuarios#index'
  get '/usuarios/new' => 'usuarios#new'
  post '/usuarios' => 'usuarios#create'
  get '/user/:id/edit_user' => 'usuarios#edit'
  post '/user/:id/update_user' => 'usuarios#update_user'
  get '/enlazar/:id' => 'points#enlazar'
  get '/enlazarEmergencias/:id' => 'points#enlazarEmergencias'
  post 'create/enlazar/:id' => 'points#cenlazar'
  post 'create/enlazarEmergencias/:id' => 'points#cenlazarEmergencias'
  get '/list/points' => 'points#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace 'api' do
    namespace 'v1' do
       resources :points
       get '/points/get/:id' => 'points#especialidades'
       get '/especialidades' => 'points#getAllespecialidades'
       get '/especialidades/:id' => 'points#getAllCentrosofEspecialidad'
       get '/emergencias' => 'points#getAllemergencias'
       get '/emergencias/:id' => 'points#getAllCentrosofEmergencia'
       get '/user' => 'points#getUser'

    end
  end
end

app/models/emergency.rb
class Emergency < ApplicationRecord
  has_many :has_emergencias
  has_many :points, through: :has_emergencias
end

app/controllers/emergencies_controller.rb
class EmergenciesController < ApplicationController
  before_action :set_emergency, only: [:show, :edit, :update, :destroy]

  # GET /emergencies
  # GET /emergencies.json
  def index
    @nombre = params[:nombre]
    if @nombre
      @specialidades = Emergency.where("name like ?", "%#{@nombre}%")
      @emergencies = @specialidades.order('name ASC')
    else
      @emergencies = Emergency.order('name ASC')
    end
  end

  # GET /emergencies/1
  # GET /emergencies/1.json
  def show
  end

  # GET /emergencies/new
  def new
    @emergency = Emergency.new
  end

  # GET /emergencies/1/edit
  def edit
  end

  # POST /emergencies
  # POST /emergencies.json
  def create
    @emergency = Emergency.new(emergency_params)

    respond_to do |format|
      if @emergency.save
        format.html { redirect_to emergencies_url, notice: '' }
        format.json { render :show, status: :created, location: @emergency }
      else
        format.html { render :new }
        format.json { render json: @emergency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergencies/1
  # PATCH/PUT /emergencies/1.json
  def update
    respond_to do |format|
      if @emergency.update(emergency_params)
        format.html { redirect_to emergencies_url, notice: '' }
        format.json { render :show, status: :ok, location: @emergency }
      else
        format.html { render :edit }
        format.json { render json: @emergency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergencies/1
  # DELETE /emergencies/1.json
  def destroy
    HasEmergencia.where(:emergency_id => @emergency.id).destroy_all
    @emergency.destroy
    respond_to do |format|
      format.html { redirect_to emergencies_url, notice: 'Emergency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency
      @emergency = Emergency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergency_params
      params.require(:emergency).permit(:name)
    end
end

app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

app/views/emergencies/_form.html.erb
<% if user_signed_in?  && current_user.role == "Administrador" %>
<%= form_with(model: emergency, local: true) do |form| %>
  <% if emergency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emergency.errors.count, "error") %> prohibited this emergency from being saved:</h2>

      <ul>
      <% emergency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :emergency_name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%else%>
<script type="text/javascript">
   window.location.href="/users/sign_in"  // put your correct path in a string here
</script>
<% end %>

app/views/emergencies/edit.html.erb
<h1>Editing Emergency</h1>

<%= render 'form', emergency: @emergency %>

<%= link_to 'Show', @emergency %> |
<%= link_to 'Back', emergencies_path %>

app/views/emergencies/index.html.erb
<div class="jumbotron container">
<div class="text-center">
  <h3>Lista de Emergencias</h3>
  <hr>
  <div class="container">
    <form action="/emergencies" method="get">
      <input class="form-control form-group" placeholder="Ingrese el nombre de la emergencia" value="<%= @nombre %>"  name=nombre type="text">
      <button class="btn btn-warning btn-block form-group" type=”submit”>Buscar</button>
    </form>
  </div>
</div>
  <br>

  <div class="container">
    <table class="table">
          <thead class="table-light">
            <tr>
              <th>#</th>
              <th>Nombre</th>
              <th>Opciones</th>
            </tr>
          </thead>
          <tbody>
            <% @count=0 %>
            <% @emergencies.each do |especialidade| %>
              <tr class="table-light">
                <td><%= @count=@count+1%></td>
                <td><%= especialidade.name %></td>
                <td><%= link_to ('<i class="fa fa-eye" aria-hidden="true"></i>').html_safe, especialidade , :class => 'btn btn-primary  btn-sm' %>
                <%if current_user.role == "Administrador"%>
                <a class="btn btn-warning btn-sm" href="#myModal<%=especialidade.id%>" data-toggle="modal" data-target="#myModal<%=especialidade.id%>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                <%= link_to  ('<i class="fa fa-trash-o" aria-hidden="true"></i>').html_safe , especialidade, :class => 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Esta seguro?' } %>
                <%end%>
               </td>
              </tr>
              <div class="modal fade" id="myModal<%=especialidade.id%>">
                <div class="modal-dialog">
                    <div class="modal-content">
                      <form action="/emergencies/<%=especialidade.id%>" method="post">
                      <input type="hidden" name="_method" value="patch">
                       <div class="modal-header">
                        <h4 class="modal-title">Editando emergencia</h4>
                       </div>
                      <div class="modal-body">
                         <div class="form-group">
                           <input  class="form-control" type="text" id="emergency_name" name="emergency[name]" value="<%= especialidade.name %>" placeholder="ingrese el nombre de la emergencia" required>
                         </div>
                      </div>
                      <div class="modal-footer">
                        <a href="#" data-dismiss="modal" class="btn btn-danger">Cancelar</a>
                        <input type="submit" class="btn btn-success" name="" value="Guardar">
                      </div>
                    </form>
                    </div>
                  </div>
              </div>
              <% end %>
          </tbody>
    </table>
  </div>
<br>
</div>

app/views/emergencies/new.html.erb
<h1>New Emergency</h1>

<%= render 'form', emergency: @emergency %>

<%= link_to 'Back', emergencies_path %>

app/views/emergencies/show.html.erb
<div class="jumbotron container">
  <div class="text-center">
    <h3><strong>  <%= @emergency.name %></strong></h3>
  </div>
  <hr>
  <h5>Centros asociados a esta emergencia: </h5>
  <br>
  <% @emergency.points.order('nombre ASC').each do |centro| %>
    <a href="/points/<%= centro.id %>" class="list-group-item list-group-item-action"><%=centro.nombre%></a>
  <% end %>
</div>