config/routes.rb
Rails.application.routes.draw do
  resources :app_users
  resources :emergencies
  resources :especialidades
  root 'welcome#index'

  devise_for :users
  resources :points
  get '/calculate/' => 'route#calculate'
  get '/usuarios' => 'usuarios#index'
  get '/usuarios/new' => 'usuarios#new'
  post '/usuarios' => 'usuarios#create'
  get '/user/:id/edit_user' => 'usuarios#edit'
  post '/user/:id/update_user' => 'usuarios#update_user'
  get '/enlazar/:id' => 'points#enlazar'
  get '/enlazarEmergencias/:id' => 'points#enlazarEmergencias'
  post 'create/enlazar/:id' => 'points#cenlazar'
  post 'create/enlazarEmergencias/:id' => 'points#cenlazarEmergencias'
  get '/list/points' => 'points#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace 'api' do
    namespace 'v1' do
       resources :points
       get '/points/get/:id' => 'points#especialidades'
       get '/especialidades' => 'points#getAllespecialidades'
       get '/especialidades/:id' => 'points#getAllCentrosofEspecialidad'
       get '/emergencias' => 'points#getAllemergencias'
       get '/emergencias/:id' => 'points#getAllCentrosofEmergencia'
       get '/user' => 'points#getUser'

    end
  end
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  validates :email, uniqueness:{ message: "ya registrado intente con otro" }
end

app/controllers/app_users_controller.rb
require 'digest/md5'

class AppUsersController < ApplicationController
  before_action :set_app_user, only: [:show, :edit, :update, :destroy]
  # GET /app_users
  # GET /app_users.json
  def index
    @app_users = AppUser.order("nombre ASC")
  end

  # GET /app_users/1
  # GET /app_users/1.json
  def show
  end

  # GET /app_users/new
  def new
    @app_user = AppUser.new
  end

  # GET /app_users/1/edit
  def edit
  end

  # POST /app_users
  # POST /app_users.json
  def create
    @app_user = AppUser.new(app_user_params)
    @app_user.password = Digest::MD5.hexdigest(@app_user.password)
    @app_user.cifrado = Digest::MD5.hexdigest(@app_user.password+@app_user.email)
      if @app_user.save
          redirect_to "/app_users/", notice: "usuario creado"
      else
        render 'new'
    end
  end

  # PATCH/PUT /app_users/1
  # PATCH/PUT /app_users/1.json
  def update

      if @app_user.update(app_user_params)
        @app_user.password = Digest::MD5.hexdigest(@app_user.password)
        @app_user.cifrado = Digest::MD5.hexdigest(@app_user.password+@app_user.email)
        @app_user.save
        redirect_to "/app_users/", notice: "usuario creado"
      else
        redirect_to "/app_users/<%=@app_user.id%>/edit", notice: "usuario creado"
      end
    end

  # DELETE /app_users/1
  # DELETE /app_users/1.json
  def destroy
    @app_user.destroy
    respond_to do |format|
      format.html { redirect_to app_users_url, notice: 'App user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_user
      @app_user = AppUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_user_params
      params.require(:app_user).permit(:nombre, :institucion, :email, :cargo, :password)
    end
end

app/helpers/app_users_helper.rb
module AppUsersHelper
end

app/views/app_users/_form.html.erb
<% if user_signed_in?  && current_user.role == "Administrador" %>
<%= form_with(model: app_user, local: true) do |form| %>
<div class="form">
  <% if app_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app_user.errors.count, "error") %>:</h2>
      <ul>
      <% app_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="form-group">
    <%= form.label :"Nombre Completo: " %>
    <%= form.text_field :nombre, id: :app_user_nombre , :class => "form-control" , :autocomplete => :off , :required => true %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, id: :app_user_email  , :class => "form-control" , :required => true %>
  </div>
  <div class="form-group">
    <%= form.label :Institucion %>
    <%= form.text_field :institucion, id: :app_user_institucion , :class => "form-control" , :autocomplete => :off , :required => true %>
  </div>
  <div class="form-group">
    <%= form.label :cargo %>
    <%= form.text_field :cargo, id: :app_user_cargo , :class => "form-control" , :autocomplete => :off , :required => true  %>
  </div>
  <div class="form-group">
    <%= form.label :Contraseña %>
    <%= form.password_field :password, id: :app_user_password , :class => "form-control" , :autocomplete => :off , :required => true %>
  </div>
  <div class="form-group">
    <%= form.label :"Confirmar Contraseña" %>
    <input type="password" id="confirm_password" class="form-control">
  </div>
  <script type="text/javascript">
      var password = document.getElementById("app_user_password")
      , confirm_password = document.getElementById("confirm_password");
    function validatePassword(){
      if(password.value != confirm_password.value) {
        confirm_password.setCustomValidity("La constraseña no coinciden");
      } else {
        confirm_password.setCustomValidity('');
      }
    }
    password.onchange = validatePassword;
    confirm_password.onkeyup = validatePassword;
  </script>
  <div class="form-group">
  <div class="actions">
    <%= form.submit 'Guardar' , :class=>"btn btn-success btn-block" , :autocomplete => :off %>
  </div>
</div>
</div>
<% end %>
<% else %>
<script type="text/javascript">
   window.location.href="/users/sign_in"  // put your correct path in a string here
</script>
<% end %>

app/views/app_users/edit.html.erb
<div class="jumbotron container">
  <div class="text-center">
    <h3>Editar informacion </h3>
  </div>
  <%= render 'form', app_user: @app_user %>
</div>

app/views/app_users/index.html.erb
<div class="jumbotron container">
<div class="text-center">
  <h3>Lista de Usuarios Aaplicación Movíl</h3>
  <hr>
  </div>
  <br>
  <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Nombre</th>
            <th>Email</th>
            <th>Cargo</th>
            <th>Institucion</th>
            <th colspan="2">Acciones:</th>
          </tr>
        </thead>
  <tbody class="table-light">
    <% @app_users.each do |app_user| %>
      <tr>
        <td><%= app_user.nombre %></td>
        <td><%= app_user.email %></td>
        <td><%= app_user.cargo %></td>
        <td><%= app_user.institucion %></td>
        <td>
        <%if current_user.role == "Administrador"%>
        <a href="/app_users/<%=app_user.id%>/edit" class="btn btn-warning btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
        <%= link_to ('<i class="fa fa-trash-o" aria-hidden="true"></i>').html_safe, app_user,:class => 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Esta seguro?' } %>
        <% end %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/app_users/new.html.erb
<div class="jumbotron container">

  <div class="text-center">
   <h3>Nuevo Usuario App Movil</h3>
  </div>
  <hr>
<%= render 'form', app_user: @app_user %>
</div>

app/views/app_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @app_user.nombre %>
</p>

<p>
  <strong>Institucion:</strong>
  <%= @app_user.institucion %>
</p>

<p>
  <strong>Email:</strong>
  <%= @app_user.email %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @app_user.cargo %>
</p>
<strong>Cargo:</strong>
<%= @app_user.password %>
</p>
<strong>cifrado:</strong>
<%= @app_user.cifrado %>
</p>


<%= link_to 'Edit', edit_app_user_path(@app_user) %> |
<%= link_to 'Back', app_users_path %>